// WARNING: This file was generated by webef-cli

///<reference path="../jspm_packages/github/opsuite/webef@master/dist/ef.d.ts" />
import "opsuite/webef";
WebEF.DBSchema.create('./schema.json');

export interface Item {
	id?: number;
	description?: string;
	deadline: Date;
	done: boolean;
	userId?: number;
	user?: User;
	tasks?: Task[];
	_ix?: number;
	_rm?: boolean;
}

export interface ItemTable extends lf.schema.Table {
	id?: lf.schema.Column;
	description?: lf.schema.Column;
	deadline: lf.schema.Column;
	done: lf.schema.Column;
	userId?: lf.schema.Column;
	_ix?: lf.schema.Column;
	_rm?: lf.schema.Column;
}

export interface ItemContext {
	item?: ItemTable;
	user?: UserTable;
	task?: TaskTable;
}

export interface Task {
	id?: number;
	itemId?: number;
	description: string;
	done: boolean;
	_ix?: number;
	_rm?: boolean;
}

export interface TaskTable extends lf.schema.Table {
	id?: lf.schema.Column;
	itemId?: lf.schema.Column;
	description: lf.schema.Column;
	done: lf.schema.Column;
	_ix?: lf.schema.Column;
	_rm?: lf.schema.Column;
}

export interface TaskContext {
	task?: TaskTable;
}

export interface User {
	id?: number;
	name: string;
	_ix?: number;
	_rm?: boolean;
}

export interface UserTable extends lf.schema.Table {
	id?: lf.schema.Column;
	name: lf.schema.Column;
	_ix?: lf.schema.Column;
	_rm?: lf.schema.Column;
}

export interface UserContext {
	user?: UserTable;
}

export interface DBMasterContext {
	item?: ItemTable;
	user?: UserTable;
	task?: TaskTable;
}

export class DBContext extends WebEF.DBContext<DBMasterContext> {
	constructor(){super('db', lf.schema.DataStoreType.WEB_SQL)}
	public item = this.DBEntity<Item, ItemContext, ItemTable>('item', ["user","task"]);
	public task = this.DBEntity<Task, TaskContext, TaskTable>('task', []);
	public user = this.DBEntity<User, UserContext, UserTable>('user', []);
}

